### Case Study - Honey Production

Source Credit : https://www.kaggle.com/jessicali9530/honey-production

#### Context
In 2006, global concern was raised over the rapid decline in the honeybee population, an integral component to American honey agriculture. Large numbers of hives were lost to Colony Collapse Disorder, a phenomenon of disappearing worker bees causing the remaining hive colony to collapse. Speculation to the cause of this disorder points to hive diseases and pesticides harming the pollinators, though no overall consensus has been reached. Twelve years later, some industries are observing recovery but the American honey industry is still largely struggling. The U.S. used to locally produce over half the honey it consumes per year. Now, honey mostly comes from overseas, with 350 of the 400 million pounds of honey consumed every year originating from imports. This dataset provides insight into honey production supply and demand in America by state from 1998 to 2012.

#### Content
The National Agricultural Statistics Service (NASS) is the primary data reporting body for the US Department of Agriculture (USDA). NASS's mission is to "provide timely, accurate, and useful statistics in service to U.S. agriculture". From datasets to census surveys, their data covers virtually all aspects of U.S. agriculture. Honey production is one of the datasets offered. Click here for the original page containing the data along with related datasets such as Honey Bee Colonies and Cost of Pollination. Data wrangling was performed in order to clean the dataset. honeyproduction.csv is the final tidy dataset suitable for analysis. The three other datasets (which include "honeyraw" in the title) are the original raw data downloaded from the site. They are uploaded to this page along with the "Wrangling The Honey Production Dataset" kernel as an example to show users how data can be wrangled into a cleaner format. Useful metadata on certain variables of the honeyproduction dataset is provided below:

  - numcol: Number of honey producing colonies. Honey producing colonies are the maximum number of colonies from which honey was taken during the year. It is possible to take honey from colonies which did not survive the entire year
  - yieldpercol: Honey yield per colony. Unit is pounds
  - totalprod: Total production (numcol x yieldpercol). Unit is pounds
  - stocks: Refers to stocks held by producers. Unit is pounds
  - priceperlb: Refers to average price per pound based on expanded sales. Unit is dollars.
  - prodvalue: Value of production (totalprod x priceperlb). Unit is dollars.
  - Other useful information: Certain states are excluded every year (ex. CT) to avoid disclosing data for individual operations. Due to rounding, total colonies multiplied by total yield may not equal production. Also, summation of states will not equal U.S. level value of production.


#### Acknowledgements
Honey production data was published by the National Agricultural Statistics Service (NASS) of the U.S. Department of Agriculture. The beautiful banner photo was by Eric Ward on Unsplash.

#### Inspiration
   - How has honey production yield changed from 1998 to 2012?
   - Over time, which states produce the most honey? Which produce the least? Which have experienced the most change in honey yield?
   - Does the data show any trends in terms of the number of honey producing colonies and yield per colony before 2006, which was when concern over Colony Collapse Disorder spread nationwide?
   - Are there any patterns that can be observed between total honey production and value of production every year?
   - How has value of production, which in some sense could be tied to demand, changed every year?
   
#### Objective
See how honey production is changed over the years (1998-2012). Over time, which states produce the most honey? Which produces the least? Are there any patterns that can be observed between total honey production and value of production every year? How has the value of production, which in some sense could be tied to demand, changed every year?

#### Steps and Tasks

- How many States are included in the dataset?
- Which are the States that are included in this dataset?
- Calculate the average production for each state across all year
- How many years of data is provided in the dataset? And what is the starting and ending year?
- Which State has seen the highest volume in production, and in which year?
- What is the average yield per colony, for each year?
- Is there a correlation between any 2 Numeric variables? Test for the same using Visual techniques
- What is the general Production trend from 1998 to 2012? Describe visually
- How is the production trend for each State? Describe visually - Hint (Use sns.FacetGrid() & g.map() functions)
- Is there a linear relationship between the Number of Colonies & Value in Production? Check at an overall level, at the state and year levels as well
- Check the distribution of total production across each year using boxplots
- How has the Value in Production changed over the years?
- What is the linear relationship between Production volume & value over the years?

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

data = pd.read_csv('honeyproduction.csv')

data.head(10)

,state,numcol,yieldpercol,totalprod,stocks,priceperlb,prodvalue,year
0,AL,16000.0,71,1136000.0,159000.0,0.72,818000.0,1998
1,AZ,55000.0,60,3300000.0,1485000.0,0.64,2112000.0,1998
2,AR,53000.0,65,3445000.0,1688000.0,0.59,2033000.0,1998
3,CA,450000.0,83,37350000.0,12326000.0,0.62,23157000.0,1998
4,CO,27000.0,72,1944000.0,1594000.0,0.70,1361000.0,1998
5,FL,230000.0,98,22540000.0,4508000.0,0.64,14426000.0,1998
6,GA,75000.0,56,4200000.0,307000.0,0.69,2898000.0,1998
7,HI,8000.0,118,944000.0,66000.0,0.77,727000.0,1998
8,ID,120000.0,50,6000000.0,2220000.0,0.65,3900000.0,1998
9,IL,9000.0,71,639000.0,204000.0,1.19,760000.0,1998

**How many states are included in the dataset?**

In [21]:
states = np.unique(data['state'])
print(len(states))

44

**Which are the states that are included in this dataset?**

In [22]:
print(states)

['AL' 'AR' 'AZ' 'CA' 'CO' 'FL' 'GA' 'HI' 'IA' 'ID' 'IL' 'IN' 'KS' 'KY'
 'LA' 'MD' 'ME' 'MI' 'MN' 'MO' 'MS' 'MT' 'NC' 'ND' 'NE' 'NJ' 'NM' 'NV'
 'NY' 'OH' 'OK' 'OR' 'PA' 'SC' 'SD' 'TN' 'TX' 'UT' 'VA' 'VT' 'WA' 'WI'
 'WV' 'WY']

**Calculate the average production for each state across all years**

In [23]:
data[['state','totalprod']].groupby('state').mean()

          totalprod
state
AL     8.254667e+05
AR     2.810400e+06
AZ     2.032267e+06
CA     2.316900e+07
CO     1.750600e+06
FL     1.646987e+07
GA     3.299933e+06
HI     8.431333e+05
IA     2.080000e+06
ID     4.410667e+06
IL     4.983333e+05
IN     4.840000e+05
KS     7.079333e+05
KY     2.296667e+05
LA     3.627333e+06
MD     2.110000e+05
ME     2.467333e+05
MI     4.854667e+06
MN     9.624000e+06
MO     8.715333e+05
MS     1.456867e+06
MT     1.043747e+07
NC     5.427333e+05
ND     3.167233e+07
NE     3.158600e+06
NJ     3.995333e+05
NM     4.764667e+05
NV     4.392727e+05
NY     3.937467e+06
OH     1.040067e+06
OK     2.011667e+05
OR     2.121400e+06
PA     1.295600e+06
SC     3.433333e+05
SD     1.774273e+07
TN     4.077333e+05
TX     6.993600e+06
UT     1.179067e+06
VA     2.665333e+05
VT     3.880667e+05
WA     2.687733e+06
WI     5.455533e+06
WV     3.212000e+05
WY     2.617933e+06

**how many years of data is provided in the dataset? And what is the starting and ending year?**

**Which state has seen the highest volume in production, and in which year?**

**What is the average yield per colony, for each year?**

**Is there a correlation between any two numeric variables? Test using visual techniques**

**What is the general production trend from 1998 to 2012? Describe visually**

**How is the production trend for each state? Describe visually**

**Is there a linear relationship between the number of colonies and value in production? Check at an overall level, at the state and year levels as well.**

**Check the distribution of total production across each year using box plots**

**How has the value in production changed over the years?**

**What is the linear relationship between production volume and value over the years?**

**How has honey production yield changed from 1998 to 2012?**

**Over time, which states produce the most honey? Which produce the least? Which have experienced the most change in honey yield?**

**Does the data show any trends in terms of the number of honey producing coloies and yield per colony before 2006, which was when concern over Colony Collapse Disorder (CCD) spread nationwide?**

**Are there any patterns that can be observed between total honey production and value of production every year?**

**How has value of production, which in some sense could be tied to demand, changed every year?**